### PR TITLE
Add support for running tests on appveyor

### PR DESCRIPTION
**Pull request by xoofx**
Followup on issue #8

### CODE REVIEW

**Comment by 0xd4d** [comment]
BTW, I think netstandard2.0 is enough, net471 can be removed.

**Comment by xoofx** [comment]
> BTW, I think netstandard2.0 is enough, net471 can be removed.

Yeah, wanted to run on a stock .NET framework instead, but with the xunit config that should be fine. There was recently some nasty issue with netstandard2.0 not being fully compatible with 4.7.1 so that's why I have put it there...
But if you prefer, we can try to use only netstandard2.0 for sure

**Comment by 0xd4d** [comment]
I think I found the problem, xunit auto detects appveyor, you can use the -noautoreporters option to disable it. I think this will solve the 10min delay.

**Comment by xoofx** [comment]
> I think I found the problem, xunit auto detects appveyor, you can use the -noautoreporters option to disable it. I think this will solve the 10min delay.

cool, good catch! I just pushed the changes, let's see how it goes...

**Comment by xoofx** [comment]
Ok it didn't worked... the configuration file does not seem to support `noautoreporter` ([here](https://github.com/xunit/xunit/blob/9d10262a3694bb099ddd783d735aba2a7aac759d/src/xunit.runner.utility/Configuration/ConfigReader_Json.cs#L176-L190))

Trying via dotnet test and a parameter on the cmd line

**Comment by xoofx** [comment]
🎉Yep it worked, you can probably merge the PR

**Comment by 0xd4d** [comment]
Thanks again, merged!

**Pull request merged**
